CREATE SEQUENCE num INCREMENT by 1 start WITH 1 MAXVALUE 99999 CYCLE;

CREATE TABLE UserContent (
    pryNumber NUMBER(5) NOT NULL PRIMARY KEY,
    IDNAME VARCHAR2(40),
    PASSWORD VARCHAR2(40),
    NAME VARCHAR2(10),
    AGE VARCHAR2(30),
    EMAIL VARCHAR2(100),
    PHONENUMBER VARCHAR2(30)
);

CREATE TABLE Room (
    RID NUMBER(4) NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(100),
    rPASSWORD VARCHAR2(30),
    USERCOUNT VARCHAR2(10),
    masterName VARCHAR2(100),
    SUBJECT VARCHAR2(30),
    condtionP NUMBER(1) DEFAULT 0
);

SELECT * FROM usercontent;